name: Build Android APK

on:
  push:
    branches: [ "main", "master", "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'

      - name: Decode Keystore
        run: |
          echo -n "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks

      - name: Build Signed Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: gradle assembleRelease

      # Pfad auf Release geändert
      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/lurkah.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lurkah-App-APK
          path: app/build/outputs/apk/release/lurkah.apk
